# Copyright (c) Alibaba, Inc. and its affiliates.
"""
Compare full vs pruned evalscope evaluation results.

Usage::

    python -m evalscope.tools.compare_runs \\
        --full ./results_full/ \\
        --pruned ./results_pruned/

Reads the report JSON files generated by ``evalscope eval`` and prints a
side-by-side accuracy comparison with the delta (pruned − full).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Optional


def _find_report(output_dir: Path) -> Optional[Path]:
    """Find the report JSON in an evalscope output directory."""
    candidates = sorted(output_dir.rglob('*.json'))
    for c in candidates:
        name = c.name.lower()
        if 'report' in name or 'result' in name:
            return c
    return candidates[0] if candidates else None


def _extract_accuracies(report_path: Path) -> Dict[str, float]:
    """Extract metric_name → value from an evalscope report JSON.

    Handles the two common shapes:
    * list of {"name": ..., "score": ...} entries
    * nested dict of {subset: {metric: value}}
    """
    data = json.loads(report_path.read_text())
    accs: Dict[str, float] = {}

    if isinstance(data, list):
        for entry in data:
            name = (
                entry.get('benchmark')
                or entry.get('dataset')
                or entry.get('name', 'unknown')
            )
            value = entry.get('score') or entry.get('acc') or entry.get('accuracy')
            if name and value is not None:
                accs[str(name)] = float(value)
    elif isinstance(data, dict):
        for key, val in data.items():
            if isinstance(val, (int, float)):
                accs[key] = float(val)
            elif isinstance(val, dict):
                for sub_key, sub_val in val.items():
                    if isinstance(sub_val, (int, float)):
                        accs[f'{key}/{sub_key}'] = float(sub_val)

    return accs


def compare(full_dir: str, pruned_dir: str) -> None:
    """Print a side-by-side comparison of two evalscope result directories."""
    full_path = Path(full_dir)
    pruned_path = Path(pruned_dir)

    full_report = _find_report(full_path)
    pruned_report = _find_report(pruned_path)

    if full_report is None:
        print(f'[compare_runs] ERROR: no report JSON found in {full_path}', file=sys.stderr)
        sys.exit(1)
    if pruned_report is None:
        print(f'[compare_runs] ERROR: no report JSON found in {pruned_path}', file=sys.stderr)
        sys.exit(1)

    full_accs = _extract_accuracies(full_report)
    pruned_accs = _extract_accuracies(pruned_report)

    print(f'\nFull report  : {full_report}')
    print(f'Pruned report: {pruned_report}')
    print(f'\n{"Metric":<45}  {"Full":>8}  {"Pruned":>8}  {"Delta":>8}')
    print('-' * 78)

    all_keys = sorted(set(full_accs) | set(pruned_accs))
    for key in all_keys:
        full_v = full_accs.get(key)
        pruned_v = pruned_accs.get(key)
        full_s = f'{full_v:.4f}' if full_v is not None else '   N/A  '
        pruned_s = f'{pruned_v:.4f}' if pruned_v is not None else '   N/A  '
        delta_s = f'{pruned_v - full_v:+.4f}' if (full_v is not None and pruned_v is not None) else '   N/A'
        print(f'{key:<45}  {full_s:>8}  {pruned_s:>8}  {delta_s:>8}')

    print()


def main() -> None:
    parser = argparse.ArgumentParser(
        prog='python -m evalscope.tools.compare_runs',
        description='Compare full vs pruned evalscope evaluation results.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--full', required=True, metavar='DIR', help='Full-benchmark output directory.')
    parser.add_argument('--pruned', required=True, metavar='DIR', help='Pruned-benchmark output directory.')
    args = parser.parse_args()
    compare(args.full, args.pruned)


if __name__ == '__main__':
    main()
